### ISSUE TITLE
Missing yield*

### ISSUE THREAD

**Issue by brghena** [lab11/accessor-files#1] opened 2015-06-20 23:31 UTC
Accessors.io should check for missing yield\* in function calls.

**Comment by ppannuto** [comment] 2015-06-21 00:04
Duplicate of https://github.com/lab11/accessors/issues/33

I have a partial implementation of this, but it's blocking on an upstream V8 bug. Specifically I can't hook generator creation at the moment.

**Closed as completed by ppannuto** 2015-06-21 00:04 UTC
